<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Ardalis.GuardClauses" Version="5.0.0" />
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="NewId" Version="4.0.1" />
    <PackageReference Include="Sieve" Version="2.5.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks\src\Core\Griffin.Core.csproj" />
    <ProjectReference Include="..\BuildingBlocks\src\EFCore\Griffin.EFCore.csproj" />
    <ProjectReference Include="..\BuildingBlocks\src\Web\Griffin.Web.csproj" />
    <ProjectReference Include="..\BuildingBlocks\src\Validation\Griffin.Validation.csproj" />
    <ProjectReference Include="..\BuildingBlocks\src\Log\Griffin.Log.csproj" />
    <ProjectReference Include="..\BuildingBlocks\src\ProblemDetails\Griffin.ProblemDetails.csproj" />
  </ItemGroup>

</Project>
